import Link from 'next/link';

import {TeacherWizard} from '@/components/teacher-wizard';
import {ActionDialog} from '@/components/action-dialog';
import {teacherIdentity} from '@/lib/teacher-identity';
import {AccountActions} from '@/components/account-actions';
import {notFound} from 'next/navigation';
import {requireUser,isManager} from '@/lib/auth';
import {demoEnabled} from '@/lib/time';
import {db} from '@/lib/db';
import {PageTitle,Panel,Empty} from '@/components/ui';

import type {RoleCode} from '@/generated/prisma/client';
import {betaUIScope} from '@/lib/beta-ui';
import {BetaScopeSwitch} from '@/components/beta-scope-switch';
const roleLabels:Record<string,string>={ADMIN:'Адміністратор',DEVELOPER:'Розробник',STUDENT:'Студент',DEAN_OFFICE:'Деканат',CURATOR:'Куратор',TEACHER:'Викладач',STAROSTA:'Староста'};
export default async function Admin({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const u=await requireUser();if(!isManager(u))notFound();
  const p=await searchParams,q=typeof p.q==='string'?p.q.slice(0,100):'',role=typeof p.role==='string'&&Object.hasOwn(roleLabels,p.role)?p.role as RoleCode:undefined;
  const tab=p.tab==='teachers'?'teachers':p.tab==='roles'?'roles':'accounts',selected=typeof p.user==='string'?p.user:undefined;
  const users=await db.user.findMany({where:{AND:[q?{OR:[{name:{contains:q,mode:'insensitive'}},{email:{contains:q,mode:'insensitive'}}]}:{},role?{roles:{some:{roleId:role}}}:{},p.status==='active'?{active:true}:p.status==='inactive'?{active:false}:{}]},select:{
    id:true,name:true,email:true,active:true,position:true,sessions:{where:{expiresAt:{gt:new Date()}},select:{id:true,device:true,lastSeenAt:true}},roles:{select:{roleId:true}},
    teacher:{select:{id:true,displayName:true}},student:{select:{id:true,fullName:true,group:{select:{name:true}}}},
    starostaAssignments:{include:{group:{select:{name:true}}}},curatorAssignments:{include:{group:{select:{name:true}}}},
    deanAssignments:{include:{faculty:{select:{name:true}}}},
  },orderBy:{email:'asc'}});
  const [groups,faculties,teachers,students]=await Promise.all([
    db.group.findMany({where:betaUIScope(u,p.scope==='faculty'),select:{id:true,name:true,specialty:{select:{facultyId:true}}},orderBy:{name:'asc'}}),
    db.faculty.findMany({select:{id:true,name:true},orderBy:{name:'asc'}}),
    db.teacher.findMany({where:{retiredAt:null},select:{id:true,displayName:true,position:true,userId:true,subjects:{include:{subject:true}},groups:{include:{group:true}},_count:{select:{lessons:{where:{startAt:{gt:new Date()},cancelled:false}}}}},orderBy:{displayName:'asc'}}),
    db.student.findMany({where:{group:betaUIScope(u,p.scope==='faculty'),active:true},select:{id:true,fullName:true,userId:true},orderBy:{fullName:'asc'}}),
  ]);
  const subjects=await db.subject.findMany({select:{id:true,name:true},orderBy:{name:'asc'}});
  const account=users.find(x=>x.id===selected);
  const path=(part:string)=>'/admin?'+new URLSearchParams({tab:part,...(p.scope==='faculty'?{scope:'faculty'}:{})});
  return <><PageTitle eyebrow="АДМІНІСТРУВАННЯ" title="Користувачі та доступ" description="Облікові записи, викладачі й призначення ролей." action={tab==='teachers'&&<TeacherWizard faculties={faculties} groups={groups.map(g=>({...g,facultyId:g.specialty.facultyId}))} subjects={subjects}/>}/><nav className="tabs" aria-label="Адміністрування">{[['accounts','Облікові записи'],['teachers','Викладачі'],['roles','Ролі та доступ']].map(([id,label])=><Link key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} href={path(id)}>{label}</Link>)}</nav>
  {tab==='accounts'&&<><BetaScopeSwitch all={p.scope==='faculty'} path="/admin"/><form className="filters"><input type="hidden" name="tab" value="accounts"/>{p.scope==='faculty'&&<input type="hidden" name="scope" value="faculty"/>}<label className="filter-wide">Ім’я або email<input name="q" defaultValue={q}/></label><label>Роль<select name="role" defaultValue={role??''}><option value="">Усі ролі</option>{Object.entries(roleLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Стан<select name="status" defaultValue={String(p.status??'')}><option value="">Усі</option><option value="active">Активні</option><option value="inactive">Вимкнені</option></select></label><button className="button primary">Знайти</button></form>
  {account&&<Panel title={teacherIdentity(account.name,account.position).name} action={<Link className="button" href={path('accounts')}>Закрити</Link>}><div className="pad stack"><p>{account.email} · {account.active?'Активний':'Вимкнений'}</p><p>{teacherIdentity(account.name,account.position).positionLabel}</p><p>Ролі: {account.roles.map(r=>roleLabels[r.roleId]).join(', ')||'Не призначено'}</p><p>Призначення: {[...account.curatorAssignments.map(a=>'Куратор '+a.group.name),...account.starostaAssignments.map(a=>'Староста '+a.group.name),...account.deanAssignments.map(a=>a.faculty.name)].join(' · ')||'Немає'}</p><p>Активних сеансів: {account.sessions.length}</p><ul>{account.sessions.map(s=><li key={s.id}>{s.device} · {s.lastSeenAt.toLocaleString('uk-UA',{timeZone:'Europe/Kyiv'})}</li>)}</ul><AccountActions actorId={u.id} demo={demoEnabled()} initialUserId={account.id} users={users.map(x=>({id:x.id,name:teacherIdentity(x.name,x.position).name+' · '+x.email,roles:x.roles.map(r=>r.roleId),teacherId:x.teacher?.id??null,studentId:x.student?.id??null,starostaGroupIds:x.starostaAssignments.map(a=>a.groupId),curatorGroupIds:x.curatorAssignments.map(a=>a.groupId),deanFacultyIds:x.deanAssignments.map(a=>a.facultyId)}))} groups={groups} faculties={faculties} teachers={teachers.map(t=>({id:t.id,name:teacherIdentity(t.displayName,t.position).name,userId:t.userId}))} students={students.map(s=>({id:s.id,name:s.fullName,userId:s.userId}))}/></div></Panel>}
  <Panel title={'Облікові записи · '+users.length}>{!users.length?<Empty>Користувачів не знайдено.</Empty>:<div className="table-scroll"><table><thead><tr><th>Ім’я / email</th><th>Стан</th><th>Ролі</th><th>Призначення</th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td><Link className="row-link" href={path('accounts')+'&user='+encodeURIComponent(x.id)}>{teacherIdentity(x.name,x.position).name}</Link><span className="table-secondary">{x.email}</span></td><td><span className="status">{x.active?'Активний':'Вимкнений'}</span></td><td>{x.roles.map(r=>roleLabels[r.roleId]).join(', ')||'Не призначено'}</td><td>{x.teacher&&<span className="table-secondary">Викладач: {teacherIdentity(x.teacher.displayName).name}</span>}{x.curatorAssignments.map(a=><span className="table-secondary" key={a.groupId}>Куратор: {a.group.name}</span>)}{x.starostaAssignments.map(a=><span className="table-secondary" key={a.groupId}>Староста: {a.group.name}</span>)}{x.deanAssignments.map(a=><span className="table-secondary" key={a.facultyId}>Деканат: {a.faculty.name}</span>)}</td></tr>)}</tbody></table></div>}</Panel></>}
  {tab==='teachers'&&<Panel title={'Викладачі · '+teachers.length}>{teachers.map(t=><details className="source-record" key={t.id}><summary>{teacherIdentity(t.displayName,t.position).name}<span className="table-secondary">{teacherIdentity(t.displayName,t.position).positionLabel}</span></summary><div className="stack pad"><p>Дисципліни: {t.subjects.map(a=>a.subject.name).join(', ')||'Не призначено'}</p><p>Групи: {t.groups.map(a=>a.group.name).join(', ')||'Не призначено'}</p><div className="inline-actions"><ActionDialog title="Змінити дисципліни" url="/api/admin/release" values={{teacherId:t.id}} label="Зберегти"><label>Дія<select name="action"><option value="ASSIGN_SUBJECT">Додати дисципліну</option><option value="REMOVE_SUBJECT">Зняти дисципліну</option></select></label><label>Дисципліна<select name="target">{subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Причина<input name="reason" minLength={5} maxLength={500} required/></label></ActionDialog><ActionDialog title="Змінити групи" url="/api/admin/release" values={{teacherId:t.id}} label="Зберегти"><label>Дія<select name="action"><option value="ASSIGN_TEACHING_GROUP">Додати групу</option><option value="REMOVE_TEACHING_GROUP">Зняти групу</option></select></label><label>Група<select name="target">{groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></label><label>Причина<input name="reason" minLength={5} maxLength={500} required/></label></ActionDialog></div><div className="danger-zone"><ActionDialog title="Архівувати викладача" url="/api/admin/release" values={{action:'RETIRE_TEACHER',teacherId:t.id,expectedFuture:t._count.lessons}} label="Архівувати" danger confirm><p>Майбутніх занять: {t._count.lessons}. Вони потребуватимуть переназначення. Навчальну історію буде збережено.</p><label>Причина<input name="reason" minLength={5} maxLength={500} required/></label></ActionDialog></div></div></details>)}</Panel>}
  {tab==='roles'&&<Panel title="Ролі та область доступу">{[['Адміністратор / Розробник','Керування системою, користувачами й призначеннями.'],['Деканат','Групи та звіти призначеного факультету.'],['Куратор','Відвідуваність і виправлення у призначених групах.'],['Викладач','Власні заняття, спільний журнал, онлайн-посилання та звіти.'],['Староста','Журнал і студенти призначеної групи.']].map(([name,description])=><div className="role-card" key={name}><h3>{name}</h3><p>{description}</p></div>)}<div className="pad"><Link className="button" href={path('accounts')}>Обрати користувача для зміни доступу</Link></div></Panel>}
  </>;
}
