import {roleLabels} from '@/lib/role-labels';
import {notFound} from 'next/navigation';
import Link from 'next/link';
import {requireUser,isManager} from '@/lib/auth';
import {db} from '@/lib/db';
import {PageTitle,Panel,Empty} from '@/components/ui';
import {ActionForm} from '@/components/action-form';
import {dateLabel,timeLabel} from '@/lib/time';
const states={NEW:'Новий',IN_PROGRESS:'У роботі',RESOLVED:'Вирішено'};
export default async function Feedback({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const u=await requireUser();if(!isManager(u))notFound();const p=await searchParams,page=Math.max(1,Math.min(10000,Number(p.page)||1)),state=p.state&&Object.hasOwn(states,p.state)?p.state:undefined;const from=p.from&&/^\d{4}-\d{2}-\d{2}$/.test(p.from)?new Date(p.from):undefined;const items=await db.feedback.findMany({where:{state,createdAt:from&&!isNaN(from.getTime())?{gte:from}:undefined,roles:p.role?{array_contains:[p.role]}:undefined},include:{user:{select:{name:true,email:true}}},orderBy:{createdAt:'desc'},skip:(page-1)*30,take:30});return <><PageTitle title="Відгуки" description="Повідомлення користувачів про роботу сайту."/><form className="filters"><label>Від дати<input name="from" type="date" defaultValue={p.from}/></label><label>Роль<select name="role" defaultValue={p.role??''}><option value="">Усі</option>{['TEACHER','STAROSTA','CURATOR','DEAN_OFFICE','ADMIN','DEVELOPER'].map(r=><option key={r} value={r}>{roleLabels[r]}</option>)}</select></label><label>Стан<select name="state" defaultValue={state??''}><option value="">Усі</option>{Object.entries(states).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="button">Застосувати</button></form><div className="section-space"><Panel title="Повідомлення">{!items.length?<Empty>Відгуків за цими фільтрами немає.</Empty>:items.map(f=><details className="source-record" key={f.id}><summary>{states[f.state as keyof typeof states]} · {f.user.name} · {dateLabel(f.createdAt)} {timeLabel(f.createdAt)}</summary><div className="pad stack"><p>{f.user.email} · {Array.isArray(f.roles)?f.roles.map(r=>roleLabels[String(r)]??String(r)).join(', '):'—'} · {f.workspace?roleLabels[f.workspace]??f.workspace:'Спільний простір'}</p><Link className="text-link" href={f.page}>Сторінка звернення</Link><p className="feedback-text">{f.text}</p><ActionForm url="/api/admin/release" values={{action:'FEEDBACK_STATE',id:f.id}} label="Змінити стан"><label>Стан<select name="state" defaultValue={f.state}>{Object.entries(states).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>Причина<input name="reason" required minLength={5} maxLength={500}/></label></ActionForm></div></details>)}</Panel></div><div className="tabs">{page>1&&<Link href={'?'+new URLSearchParams({...p,page:String(page-1)} as Record<string,string>)}>Попередня</Link>}{items.length===30&&<Link href={'?'+new URLSearchParams({...p,page:String(page+1)} as Record<string,string>)}>Наступна</Link>}</div></>;}
