import {notFound} from 'next/navigation';
import Link from 'next/link';
import {requireUser,isManager,hasRole} from '@/lib/auth';
import {db} from '@/lib/db';
import {PageTitle,Panel,Empty} from '@/components/ui';
import {ActionDialog} from '@/components/action-dialog';
import {TermCreate} from '@/components/term-create';
import {readableRange} from '@/lib/report-presentation';
import {today} from '@/lib/time';
export default async function Terms({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const u=await requireUser();if(!isManager(u)&&!hasRole(u,'DEAN_OFFICE'))notFound();const archive=(await searchParams).tab==='archive';
 const faculties=await db.faculty.findMany({where:isManager(u)?{}:{id:{in:u.deanAssignments.map(a=>a.facultyId)}}});
 const terms=await db.academicTerm.findMany({where:{facultyId:{in:faculties.map(f=>f.id)},archivedAt:archive?{not:null}:null},include:{faculty:true,_count:{select:{lessons:true}}},orderBy:{fromDate:'desc'},take:50});
 const cards=await Promise.all(terms.map(async t=>{const roster=await db.lessonStudent.findMany({where:{lesson:{termId:t.id}},distinct:['studentId','groupId'],select:{studentId:true,groupId:true}});const draft=await db.auditLog.findFirst({where:{objectType:'AcademicTerm',objectId:t.id,source:'TERM_CREATE'},select:{details:true}});return {...t,roster,draft:(draft?.details as {rosterDraft?:{id:string;groupId:string;fullName:string}[]}|null)?.rosterDraft};}));
 return <><PageTitle eyebrow="НАВЧАЛЬНІ ПЕРІОДИ" title="Семестри" description="Поточна робота та історія завершених семестрів." action={isManager(u)&&<TermCreate faculties={faculties}/>}/><nav className="tabs" aria-label="Семестри"><Link className={!archive?'active':''} aria-current={!archive?'page':undefined} href="/terms">Поточні</Link><Link className={archive?'active':''} aria-current={archive?'page':undefined} href="/terms?tab=archive">Архів</Link></nav>{!cards.length&&<Panel><Empty>{archive?'Завершених семестрів поки немає.':'Семестри ще не створено.'}</Empty></Panel>}{cards.map(t=><Panel key={t.id} title={t.name} action={<span className="status">{t.archivedAt?'Архів · Лише читання':t.fromDate>today()?'Запланований':t.toDate<today()?'Період минув':'Активний'}</span>}><div className="pad stack"><p>{readableRange(t.fromDate,t.toDate)}</p><p className="muted">{t.faculty.name}</p><span className={'status '+(t.rosterConfirmedAt?'status-PRESENT':'')}>{t.rosterConfirmedAt?'Склад підтверджено':t.draft?'Чернетка складу · Не підтверджено':'Склад не підтверджено'}</span><dl className="term-stats"><div><dt>Групи у заняттях</dt><dd>{new Set(t.roster.map(r=>r.groupId)).size}</dd></div><div><dt>Студенти у складі занять</dt><dd>{new Set(t.roster.map(r=>r.studentId)).size}</dd></div><div><dt>Заняття</dt><dd>{t._count.lessons}</dd></div></dl><div className="inline-actions"><Link className="button primary" href={'/reports?term='+t.id+'&from='+t.fromDate+'&to='+t.toDate}>Звіти семестру</Link><Link className="button" href={'/groups?term='+t.id+'&from='+t.fromDate+'&to='+t.toDate}>Переглянути склад</Link></div>{t.draft&&<details><summary>Чернетка на момент створення · {t.draft.length} студентів</summary><ul>{t.draft.map(s=><li key={s.id}>{s.fullName}</li>)}</ul><p className="muted small">Перед підтвердженням перевірте поточний склад груп. Підтвердження використовує актуальних активних студентів.</p></details>}{!t.archivedAt&&!t.rosterConfirmedAt&&isManager(u)&&<ActionDialog title="Підтвердити склад" url="/api/terms" values={{action:'CONFIRM_ROSTER',termId:t.id}} label="Підтвердити склад" confirm><p>Поточні активні студенти будуть додані до наявних майбутніх занять цього семестру. Перегляньте склад груп перед підтвердженням.</p><label>Причина<input name="reason" minLength={5} maxLength={500} required/></label></ActionDialog>}{!t.archivedAt&&<div className="danger-zone"><ActionDialog title="Завершити семестр" url="/api/terms" values={{action:'ARCHIVE',termId:t.id}} label="Завершити семестр" danger confirm><p className="form-error">Після завершення відмітки, заняття та історичний склад неможливо змінити. Семестр залишиться доступним для перегляду і звітів.</p><label>Причина завершення<input name="reason" minLength={5} maxLength={500} required/></label></ActionDialog></div>}</div></Panel>)}</>;
}
