import {auditTitle} from '@/lib/audit-presentation';
import {displayName} from '@/lib/display-name';
import {AttendanceModeChange} from '@/components/attendance-mode-change';
import {DateTime} from 'luxon';
import {notFound} from 'next/navigation';
import Link from 'next/link';
import {requireUser,isManager} from '@/lib/auth';
import {db} from '@/lib/db';
import {PageTitle,Panel,Status} from '@/components/ui';
import {dateLabel,timeLabel} from '@/lib/time';
export default async function Audit({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const u=await requireUser();if(!isManager(u))notFound();const p=await searchParams,page=Math.max(1,Math.min(10000,Number(p.page)||1)),source=p.source?.slice(0,80),objectType=p.type?.slice(0,80);const from=/^\d{4}-\d{2}-\d{2}$/.test(p.from??'')?p.from:undefined,to=/^\d{4}-\d{2}-\d{2}$/.test(p.to??'')?p.to:undefined;const rows=await db.auditLog.findMany({where:{createdAt:{gte:from?DateTime.fromISO(from,{zone:'Europe/Kyiv'}).toJSDate():undefined,lt:to?DateTime.fromISO(to,{zone:'Europe/Kyiv'}).plus({days:1}).toJSDate():undefined},source:source?{contains:source}:undefined,objectType:objectType||undefined},include:{actor:{select:{name:true}}},orderBy:{createdAt:'desc'},take:50,skip:(page-1)*50});return <><PageTitle title="Аудит" description="Вхід, паролі, ролі, склад, відвідуваність і технічні операції."/><form className="filters"><label>Від<input type="date" name="from" defaultValue={from}/></label><label>До<input type="date" name="to" defaultValue={to}/></label><label>Джерело / дія<input name="source" defaultValue={source}/></label><label>Об’єкт<select name="type" defaultValue={objectType??''}><option value="">Усі</option>{['Login','User','UserAssignment','Administration','Student','Attendance','Lesson','Report','Feedback','AcademicTerm','RosterImport','BackfillBatch','SystemError'].map(t=><option key={t}>{t}</option>)}</select></label><button className="button">Застосувати</button></form><div className="section-space"><Panel title="Останні події">{rows.map(a=><details className="source-record" key={a.id}><summary>{dateLabel(a.createdAt)} {timeLabel(a.createdAt)} · {a.actor?displayName(a.actor.name):'Технічний запуск'} · {auditTitle(a)}</summary><p>Джерело: {a.source} · {a.objectType}</p><p>Об’єкт: {a.objectId}</p><p>Причина: {a.reason??'—'}</p>{a.objectType==='Attendance'&&<div className="history-change"><Status value={a.oldStatus}/><span>→</span><Status value={a.newStatus}/><AttendanceModeChange details={a.details}/></div>}<pre className="feedback-text">{JSON.stringify(a.details,null,2)}</pre></details>)}</Panel></div><div className="tabs">{page>1&&<Link href={'?'+new URLSearchParams({...p,page:String(page-1)} as Record<string,string>)}>Попередня</Link>}{rows.length===50&&<Link href={'?'+new URLSearchParams({...p,page:String(page+1)} as Record<string,string>)}>Наступна</Link>}</div></>;}
