import {LinkedRow} from '@/components/linked-row';
import {SortHeader} from '@/components/sort-header';
import {sortRows} from '@/lib/sorting';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireUser} from '@/lib/auth';
import {db} from '@/lib/db';
import {groupScope} from '@/lib/access';
import {analytics,filterOptions} from '@/lib/analytics';
import {parseFilters,filterLink,type Search} from '@/lib/filters';
import {Filters} from '@/components/filters';
import {Breadcrumbs,PageTitle,Panel,Stats,Empty,Percentage,Completion,FormulaNote} from '@/components/ui';
export default async function SpecialtyPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Search>}){const u=await requireUser(),{id}=await params,f=parseFilters(await searchParams);const s=await db.specialty.findFirst({where:{id,groups:{some:groupScope(u)}},include:{faculty:true}});if(!s)notFound();Object.assign(f,{faculty:s.facultyId,specialty:id,student:undefined});const data=await analytics(u,{...f,specialty:id}),options=await filterOptions(u);return <><Breadcrumbs items={[{label:s.faculty.name,href:filterLink('/',f,{specialty:undefined,group:undefined,student:undefined})},{label:s.name}]}/><PageTitle eyebrow="СПЕЦІАЛЬНІСТЬ" title={s.name} description={s.codeNote??s.code??'Код не вказаний у джерелі'}/><Filters value={f} options={options} hide={['specialty','group']}/><Stats data={data} filters={f}/><Panel><Completion data={data}/></Panel><div className="section-space"><Panel title="Навчальні групи">{data.groups.length?<div className="table-scroll"><table><thead><tr><SortHeader label="Група" sortKey="groups_name" filters={f} path={`/specialties/${id}`}/><SortHeader label="Курс" sortKey="groups_course" filters={f} path={`/specialties/${id}`}/><SortHeader label="Студенти" sortKey="groups_students" filters={f} path={`/specialties/${id}`}/><SortHeader label="Заняття" sortKey="groups_lessons" filters={f} path={`/specialties/${id}`}/><SortHeader label="Відвідуваність" sortKey="groups_percentage" filters={f} path={`/specialties/${id}`}/></tr></thead><tbody>{sortRows(data.groups,f,{groups_name:g=>g.name,groups_course:g=>g.course,groups_students:g=>g.students.length,groups_lessons:g=>g.lessonCount,groups_percentage:g=>g.stats.percentage}).map(g=><LinkedRow key={g.id} href={filterLink(`/groups/${g.id}`,f,{group:g.id,student:undefined})}><td><Link className="row-link" href={filterLink(`/groups/${g.id}`,f,{group:g.id,student:undefined})}>{g.name}</Link></td><td>{g.course}</td><td>{g.students.length}</td><td>{g.lessonCount}</td><td><Percentage value={g.stats.percentage}/></td></LinkedRow>)}</tbody></table></div>:<Empty>На обраному курсі немає підтверджених груп цієї спеціальності.</Empty>}</Panel></div><FormulaNote/></>;}
