import {teacherIdentity} from '@/lib/teacher-identity';
import {filterLink,type Filters} from '@/lib/filters';
import Link from 'next/link';
import {journalStateForRoster,journalStateLabel} from '@/lib/journal-state';
import {dateLabel,timeLabel} from '@/lib/time';
import {Empty} from './ui';
type Lesson={id:string;startAt:Date;endAt:Date;pairNumber:number;room:string;onlineUrl?:string|null;teacher?:{displayName:string;position?:string}|null;cancelled:boolean;journalState:string;subject:{name:string};building:{abbreviation:string};groups:{group:{name:string}}[];attendance:{statusCode:string;confirmed:boolean}[];_count:{roster:number}};
export function LessonList({lessons,filters}:{lessons:Lesson[];filters?:Filters}){return lessons.length?<div className="lesson-grid">{lessons.map(l=>{const counts={PRESENT:0,N:0,HV:0};for(const a of l.attendance)counts[a.statusCode as keyof typeof counts]++;const state=journalStateForRoster(l._count.roster,l.attendance);return <article key={l.id} className="lesson-card"><div className="lesson-meta"><span>{dateLabel(l.startAt)} · {l.pairNumber} пара</span><span>{timeLabel(l.startAt)}–{timeLabel(l.endAt)}</span></div><h2><Link href={filters?filterLink(`/teacher/lessons/${l.id}`,filters):`/teacher/lessons/${l.id}`}>{l.subject.name}</Link></h2><p className="muted small">{l.teacher?teacherIdentity(l.teacher.displayName,l.teacher.position).name:'Викладача не призначено'}{l.teacher&&<span className="table-secondary">{teacherIdentity(l.teacher.displayName,l.teacher.position).positionLabel}</span>}</p>{l.onlineUrl?<a className="text-link" href={l.onlineUrl} target="_blank" rel="noopener noreferrer">Онлайн-заняття ↗</a>:<span className="muted small">Онлайн-посилання не вказано</span>}<div className="lesson-meta"><span>{l.groups.map(g=>g.group.name).join(' + ')}</span><span>{l.building.abbreviation} {l.room}</span></div><div><span className="tag">{l.cancelled?'Скасовано':journalStateLabel(state)}</span></div><div className="lesson-counts"><span className="success">• {counts.PRESENT}</span><span className="danger">N {counts.N}</span><span className="info">HV {counts.HV}</span><span className="muted">Не відмічено: {l._count.roster-l.attendance.length}</span><Link className="text-link" style={{marginLeft:'auto'}} href={filters?filterLink(`/teacher/lessons/${l.id}`,filters):`/teacher/lessons/${l.id}`}>Відкрити →</Link></div></article>;})}</div>:<PanelEmpty/>;}
function PanelEmpty(){return <div className="panel section-space"><Empty>За обраною датою або пошуком занять немає.</Empty></div>;}
