'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
const positions={UNSPECIFIED:'Не вказано',ASSISTANT:'Асистент',SENIOR_LECTURER:'Старший викладач',DOCENT:'Доцент',PROFESSOR:'Професор'};
export function ProfileForm({name='',position='UNSPECIFIED',passwordOnly=false}:{name?:string;position?:string;passwordOnly?:boolean}){
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failed,setFailed]=useState(false);const router=useRouter();
  async function submit(form:HTMLFormElement){setBusy(true);setMessage('');setFailed(false);try{const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await r.json();if(!r.ok)throw new Error(data.error);form.reset();setMessage('Зміни збережено.');if(data.destination)router.push(data.destination);router.refresh();}catch(e){setFailed(true);setMessage(e instanceof Error?e.message:'Помилка збереження.');}finally{setBusy(false);}}
  return <div className="pad stack">{!passwordOnly&&<form className="filters" onSubmit={e=>{e.preventDefault();void submit(e.currentTarget);}}><input type="hidden" name="action" value="PROFILE"/><label>ПІБ<input name="name" defaultValue={name} minLength={2} maxLength={200} required/></label><label>Посада<select name="position" defaultValue={position}>{Object.entries(positions).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button className="button primary" disabled={busy}>Зберегти профіль</button></form>}
    <form className="filters" onSubmit={e=>{e.preventDefault();void submit(e.currentTarget);}}><input type="hidden" name="action" value="PASSWORD"/><label>Поточний / тимчасовий пароль<input name="currentPassword" type="password" autoComplete="current-password" required maxLength={128}/></label><label>Новий пароль<input name="newPassword" type="password" autoComplete="new-password" required minLength={10} maxLength={128}/></label><button className="button primary" disabled={busy}>{busy?'Збереження…':'Змінити пароль'}</button></form>
    {message&&<p role={failed?'alert':'status'} className={failed?'error-text':'form-success'}>{message}</p>}</div>;
}
export function SessionActions({sessions}:{sessions:{id:string;device:string;lastSeen:string;current:boolean}[]}){
  const router=useRouter();const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function revoke(sessionId?:string){setBusy(true);try{const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(sessionId?{action:'REVOKE_SESSION',sessionId}:{action:'REVOKE_ALL'})});const data=await r.json();if(!r.ok)throw new Error(data.error);if(data.destination)router.push(data.destination);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Помилка');}finally{setBusy(false);}}
  return <div className="pad stack">{sessions.map(s=><div className="session-row" key={s.id}><div><strong>{s.device}{s.current?' · Поточний сеанс':''}</strong><p className="muted small">{s.lastSeen} · Місце невідоме</p></div><button className="button" disabled={busy} onClick={()=>void revoke(s.id)}>Завершити</button></div>)}<button className="button" disabled={busy} onClick={()=>void revoke()}>Вийти з усіх пристроїв</button>{message&&<p role="alert">{message}</p>}</div>;
}
