'use client';
import {useState} from 'react';
import Link from 'next/link';
import {filterLink} from '@/lib/filters';
import {teacherIdentity} from '@/lib/teacher-identity';
import type {ReportFilters,ReportSummary} from '@/lib/report-types';
import {Percentage,Empty} from './ui';
export function ReportTables({summary,filters}:{summary:ReportSummary;filters:ReportFilters}){
 const [view,setView]=useState(filters.view??'STUDENTS');
 const rows=[...(summary.rows??[])].sort((a,b)=>(a.stats.percentage??Infinity)-(b.stats.percentage??Infinity)||a.fullName.localeCompare(b.fullName,'uk'));
 const oneTeacher=new Set(summary.lessons?.map(l=>l.teacher)).size===1;
 return <><div className="filter-section tabs report-view-tabs" role="group" aria-label="Таблиця звіту">{(['STUDENTS','LESSONS'] as const).map(v=><button type="button" key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v==='STUDENTS'?'Студенти':'Пари'}</button>)}</div>{view==='STUDENTS'?(rows.length?<div className="table-scroll"><table className="report-data-table"><thead><tr>{['ПІБ','Група','Всього занять','PRESENT','N','HV','Онлайн','Офлайн','Не відмічено','Показник %'].map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.groupId+':'+s.id}><td><Link className="row-link" href={filterLink('/students/'+s.id,filters)}>{s.fullName}</Link></td><td>{s.groupName}</td><td>{s.stats.expected}</td><td>{s.stats.PRESENT}</td><td>{s.stats.N}</td><td>{s.stats.HV}</td><td>{s.stats.ONLINE??0}</td><td>{s.stats.OFFLINE??0}</td><td>{s.stats.unmarked}</td><td><Percentage value={s.stats.percentage}/></td></tr>)}</tbody></table></div>:<Empty>{summary.students?'Звіт попередньої версії. Дані доступні у збережених файлах.':'За обраний період даних немає.'}</Empty>):(summary.lessons?.length?<div className="table-scroll"><table className="report-data-table"><thead><tr>{['Дата','Пара','Дисципліна','Група','Склад','PRESENT','N','HV','Онлайн','Офлайн','Не відмічено','Показник %'].map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{summary.lessons.map(l=><tr key={l.lessonId+':'+l.groupId}><td><Link href={filterLink('/teacher/lessons/'+l.lessonId,filters)}>{l.date.split('-').reverse().join('.')}<span className="table-secondary">{l.time}</span></Link></td><td>{l.pair}</td><td className="report-subject">{l.subject}{!oneTeacher&&<span className="table-secondary">{teacherIdentity(l.teacher).name}</span>}{l.onlineUrl&&<a className="table-secondary" href={l.onlineUrl} target="_blank" rel="noopener noreferrer">Онлайн-заняття ↗</a>}</td><td>{l.group}</td><td>{l.stats.expected}</td><td>{l.stats.PRESENT}</td><td>{l.stats.N}</td><td>{l.stats.HV}</td><td>{l.stats.ONLINE??0}</td><td>{l.stats.OFFLINE??0}</td><td>{l.stats.unmarked}</td><td><Percentage value={l.stats.percentage}/></td></tr>)}</tbody></table></div>:<Empty>Цей знімок не містить окремої таблиці пар.</Empty>)}</>;
}
