'use client';
import {useRouter} from 'next/navigation';
import {useState} from 'react';
import {DateTime} from 'luxon';
import type {ReportFilters,ReportKind} from '@/lib/report-types';
import {readableRange,selectedPeriod} from '@/lib/report-presentation';
import {FilterBar,SectionCard} from './design-system';
export type ReportOptions={subjects?:{id:string;name:string}[];faculties:{id:string;name:string}[];specialties:{id:string;name:string;facultyId:string}[];groups:{id:string;name:string;specialtyId:string;course:number}[];students:{id:string;fullName:string;groupId:string}[];terms:{id:string;name:string;facultyId:string;fromDate:string;toDate:string;archived:boolean}[]};
export function ReportForm({filters,options,periods}:{filters:ReportFilters;options:ReportOptions;periods:Record<'DAILY'|'WEEKLY'|'MONTHLY',{from:string;to:string}>}){
 const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [faculty,setFaculty]=useState(filters.faculty??options.specialties[0]?.facultyId??options.faculties[0]?.id??''),[course,setCourse]=useState(filters.course?String(filters.course):''),[group,setGroup]=useState(filters.group??''),[student,setStudent]=useState(filters.student??''),[subject,setSubject]=useState(filters.subject??''),[threshold,setThreshold]=useState(filters.threshold?String(filters.threshold):'');
 const [kind,setKind]=useState<ReportKind>(filters.term?'SEMESTER':'WEEKLY'),[view,setView]=useState(filters.view??'STUDENTS'),[term,setTerm]=useState(filters.term??options.terms.find(t=>!t.archived&&t.facultyId===faculty)?.id??''),[dates,setDates]=useState({from:filters.from,to:filters.to});
 const terms=options.terms.filter(t=>t.facultyId===faculty),selectedTerm=terms.find(t=>t.id===term);
 const range=kind==='SEMESTER'&&selectedTerm?{from:selectedTerm.fromDate,to:selectedTerm.toDate}:dates;
 const groups=options.groups.filter(g=>options.specialties.some(s=>s.id===g.specialtyId&&s.facultyId===faculty)&&(!course||g.course===Number(course)));
 const students=options.students.filter(s=>groups.some(g=>g.id===s.groupId)&&(!group||s.groupId===group));
 function changeKind(next:ReportKind){setKind(next);setMessage('');if(next==='WEEKLY'||next==='MONTHLY')setDates(periods[next]);}
 return <SectionCard><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({faculty,kind,view,...range,course,group,subject,student:view==='STUDENTS'?student:'',threshold:view==='STUDENTS'?threshold:'',term:kind==='SEMESTER'?term:undefined,scope:filters.scope,specialty:options.specialties.filter(s=>s.facultyId===faculty).length===1?options.specialties.find(s=>s.facultyId===faculty)?.id:undefined})});const result=await r.json();if(!r.ok)throw new Error(result.error);if(result.state==='READY')router.push('/reports/'+result.id);else setMessage('Звіт формується. Оновіть список за мить.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Не вдалося створити звіт.');}finally{setBusy(false);}}}>
 <fieldset disabled={busy} className="plain-fieldset"><div className="filter-section"><FilterBar><label>Період<select aria-label="Період" value={kind} onChange={e=>changeKind(e.target.value as ReportKind)}><option value="WEEKLY">Тиждень</option><option value="MONTHLY">Місяць</option><option value="SEMESTER">Семестр</option><option value="CUSTOM">Довільний</option></select></label>
 {kind==='WEEKLY'&&<label>Тиждень<input type="week" required value={DateTime.fromISO(dates.from).toFormat("kkkk-'W'WW")} onChange={e=>{const next=selectedPeriod('WEEKLY',e.target.value);if(next)setDates(next);}}/></label>}
 {kind==='MONTHLY'&&<label>Місяць<input type="month" required value={dates.from.slice(0,7)} onChange={e=>{const next=selectedPeriod('MONTHLY',e.target.value);if(next)setDates(next);}}/></label>}
 {kind==='SEMESTER'&&<label className="filter-wide">Семестр<select required value={term} onChange={e=>setTerm(e.target.value)}><option value="">Оберіть семестр</option>{terms.map(t=><option key={t.id} value={t.id}>{t.name}{t.archived?' · Архів':''}</option>)}</select></label>}
 {kind==='CUSTOM'&&<><label>Від<input type="date" required value={dates.from} onChange={e=>setDates({...dates,from:e.target.value})}/></label><label>До<input type="date" required min={dates.from} value={dates.to} onChange={e=>setDates({...dates,to:e.target.value})}/></label></>}
 <button type="button" className="button" onClick={()=>changeKind('WEEKLY')}>Поточний тиждень</button></FilterBar><p className="period-range range-note">{readableRange(range.from,range.to)}</p></div>
 <div className="filter-section"><div className="tabs" role="group" aria-label="Вид звіту">{(['STUDENTS','LESSONS'] as const).map(v=><button key={v} type="button" aria-pressed={view===v} onClick={()=>setView(v)}>{v==='STUDENTS'?'Студенти':'Пари'}</button>)}</div></div>
 <div className="filter-section"><FilterBar>{options.faculties.length>1&&<label className="filter-wide">Факультет<select value={faculty} onChange={e=>{setFaculty(e.target.value);setGroup('');setStudent('');setSubject('');setTerm(options.terms.find(t=>!t.archived&&t.facultyId===e.target.value)?.id??'');}}>{options.faculties.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}<label>Курс<select value={course} onChange={e=>{setCourse(e.target.value);setGroup('');setStudent('');}}><option value="">Усі курси</option>{[1,2,3,4].map(c=><option key={c} value={c}>{c} курс</option>)}</select></label><label>Група<select value={group} onChange={e=>{setGroup(e.target.value);setStudent('');}}><option value="">Усі групи</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>
 {view==='STUDENTS'&&<><label className="filter-wide">Студент / студентка<select value={student} onChange={e=>setStudent(e.target.value)}><option value="">Усі студенти</option>{students.map(s=><option key={s.id} value={s.id}>{s.fullName}</option>)}</select></label><label>Поріг<select value={threshold} onChange={e=>setThreshold(e.target.value)}><option value="">Усі показники</option><option value="70">Нижче 70%</option><option value="50">Нижче 50%</option></select></label></>}
 <label className="filter-wide">Дисципліна<select value={subject} onChange={e=>setSubject(e.target.value)}><option value="">Усі дисципліни</option>{options.subjects?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></FilterBar></div>
 <div className="filter-section inline-actions"><button className="button primary" disabled={!faculty||(kind==='SEMESTER'&&!selectedTerm)}>{busy?'Створення…':'Створити звіт'}</button>{message&&<p className="error-text" role="alert">{message}</p>}</div></fieldset></form></SectionCard>;
}
