'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Dialog} from './dialog';
import {MultiSelect} from './multi-select';
import {positions,teacherIdentity} from '@/lib/teacher-identity';
type Option={id:string;name:string};
export function TeacherWizard({faculties,groups,subjects}:{faculties:Option[];groups:(Option&{facultyId?:string})[];subjects:Option[]}){
 const router=useRouter(),[open,setOpen]=useState(false),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[password,setPassword]=useState(''),[copied,setCopied]=useState(false);
 const [identity,setIdentity]=useState({name:'',position:'UNSPECIFIED',email:'',facultyId:faculties[0]?.id??''}),[roles,setRoles]=useState<string[]>([]),[selectedSubjects,setSubjects]=useState<string[]>([]),[selectedGroups,setGroups]=useState<string[]>([]);
 const titles=['Особисті дані','Ролі','Навчальне навантаження','Підтвердження'];
 function close(){setOpen(false);setPassword('');setError('');}
 function start(){setIdentity({name:'',position:'UNSPECIFIED',email:'',facultyId:faculties[0]?.id??''});setRoles([]);setSubjects([]);setGroups([]);setPassword('');setCopied(false);setStep(0);setError('');setOpen(true);}
 return <><button className="button primary" onClick={start}>Створити викладача</button>{open&&<Dialog title={password?'Викладача створено':'Новий викладач'} busy={busy} onClose={close}>{password?<div className="pad stack"><p>{identity.email}</p><p>Тимчасовий пароль показано лише зараз. При першому вході його потрібно змінити.</p><code className="credential">{password}</code><button className="button" onClick={async()=>{try{await navigator.clipboard.writeText(identity.email+'\n'+password);setCopied(true);}catch{setError('Скопіюйте пароль вручну.');}}}>{copied?'Скопійовано':'Копіювати email і пароль'}</button>{error&&<p role="alert">{error}</p>}<button className="button primary" onClick={close}>Готово</button></div>:<><ol className="wizard-steps">{titles.map((t,i)=><li className={step===i?'current':''} aria-current={step===i?'step':undefined} key={t}>{i+1}. {t}</li>)}</ol><form className="pad stack" onSubmit={async e=>{e.preventDefault();if(step<3){setStep(step+1);return;}setBusy(true);setError('');try{const r=await fetch('/api/admin/release',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...identity,name:teacherIdentity(identity.name).name,action:'CREATE_TEACHER',roles:['TEACHER',...roles],subjects:selectedSubjects,groups:selectedGroups})});const data=await r.json();if(!r.ok)throw new Error(data.error);setPassword(data.password);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Помилка');}finally{setBusy(false);}}}><fieldset disabled={busy} className="plain-fieldset wizard-body stack">
 {step===0&&<div className="form-grid"><label className="full-row">ПІБ<input autoFocus required minLength={2} maxLength={200} value={identity.name} onChange={e=>setIdentity({...identity,name:e.target.value})}/></label><label>Посада<select value={identity.position} onChange={e=>setIdentity({...identity,position:e.target.value})}>{Object.entries(positions).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Email<input type="email" required maxLength={200} value={identity.email} onChange={e=>setIdentity({...identity,email:e.target.value})}/></label><label className="full-row">Факультет<select required value={identity.facultyId} onChange={e=>{setIdentity({...identity,facultyId:e.target.value});setGroups([]);}}>{faculties.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div>}
 {step===1&&<><p><span className="status status-PRESENT">Викладач</span> · Основна роль</p><MultiSelect name="roles" label="Додаткові ролі" options={[{id:'CURATOR',name:'Куратор'},{id:'DEAN_OFFICE',name:'Деканат'}]} value={roles} onChange={setRoles}/></>}
 {step===2&&<><MultiSelect name="subjects" label="Дисципліни" options={subjects} value={selectedSubjects} onChange={setSubjects}/><MultiSelect name="groups" label="Групи" options={groups.filter(g=>!g.facultyId||g.facultyId===identity.facultyId)} value={selectedGroups} onChange={setGroups}/><p className="small muted">Обрані групи визначають навчальне навантаження{roles.includes('CURATOR')?' і групи куратора':''}. Заняття розкладу призначаються окремо.</p></>}
 {step===3&&<><h3>{teacherIdentity(identity.name).name}</h3><p>{positions[identity.position as keyof typeof positions]} · {identity.email}</p><p>{faculties.find(f=>f.id===identity.facultyId)?.name}</p><p>Ролі: Викладач{roles.includes('CURATOR')?', Куратор':''}{roles.includes('DEAN_OFFICE')?', Деканат':''}</p><p>Дисципліни: {subjects.filter(s=>selectedSubjects.includes(s.id)).map(s=>s.name).join(', ')||'Не призначено'}</p><p>Групи: {groups.filter(g=>selectedGroups.includes(g.id)).map(g=>g.name).join(', ')||'Не призначено'}</p><p className="small muted">Після створення буде показано тимчасовий пароль.</p></>}
 </fieldset>{error&&<p className="error-text" role="alert">{error}</p>}<div className="wizard-footer"><button className="button" type="button" disabled={busy} onClick={()=>step?setStep(step-1):close()}>{step?'Назад':'Скасувати'}</button><button className="button primary" disabled={busy}>{busy?'Створення…':step===3?'Створити й видати пароль':'Далі'}</button></div></form></>}</Dialog>}</>;
}
