import {LinkedRow} from '@/components/linked-row';
import {SortHeader} from '@/components/sort-header';
import {sortRows} from '@/lib/sorting';
import Link from 'next/link';
import {requireUser} from '@/lib/auth';
import {analytics,filterOptions} from '@/lib/analytics';
import {parseFilters,filterLink,type Search} from '@/lib/filters';
import {Filters} from '@/components/filters';
import {PageTitle,Panel,Empty,Percentage} from '@/components/ui';
export default async function Groups({searchParams}:{searchParams:Promise<Search>}){const u=await requireUser(),f=parseFilters(await searchParams),data=await analytics(u,f);return <><PageTitle eyebrow="НАВЧАЛЬНА СТРУКТУРА" title="Групи та студенти" description="Доступні вам групи та їхня відвідуваність."/><Filters value={f} options={await filterOptions(u)}/><div className="section-space"><Panel title={`Навчальні групи · ${data.groups.length}`}>{data.groups.length?<div className="table-scroll"><table><thead><tr><SortHeader label="Група" sortKey="groups_name" filters={f} path={'/groups'}/><SortHeader label="Курс" sortKey="groups_course" filters={f} path={'/groups'}/><SortHeader label="Спеціальність" sortKey="groups_specialty" filters={f} path={'/groups'}/><SortHeader label="Студенти" sortKey="groups_students" filters={f} path={'/groups'}/><SortHeader label="Показник" sortKey="groups_percentage" filters={f} path={'/groups'}/></tr></thead><tbody>{sortRows(data.groups,f,{groups_name:g=>g.name,groups_course:g=>g.course,groups_specialty:g=>g.specialty.name,groups_students:g=>g.students.length,groups_percentage:g=>g.stats.percentage}).map(g=><LinkedRow key={g.id} href={filterLink(`/groups/${g.id}`,f,{faculty:g.specialty.facultyId,specialty:g.specialtyId,group:g.id,student:undefined})}><td><Link className="row-link" href={filterLink(`/groups/${g.id}`,f,{faculty:g.specialty.facultyId,specialty:g.specialtyId,group:g.id,student:undefined})}>{g.name}</Link></td><td>{g.course}</td><td><Link href={filterLink(`/specialties/${g.specialtyId}`,f,{faculty:g.specialty.facultyId,specialty:g.specialtyId,group:undefined,student:undefined})}>{g.specialty.name}</Link></td><td>{g.students.length}</td><td><Percentage value={g.stats.percentage}/></td></LinkedRow>)}</tbody></table></div>:<Empty>Немає доступних груп. Перевірте фільтри або призначення.</Empty>}</Panel></div></>;}
